# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'document_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64ocument_service.proto\x12\x16nexus.document_service\"L\n\x0f\x44ocumentRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\"x\n\x10ProcessingStatus\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1b\n\x13progress_percentage\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t2z\n\x10\x44ocumentIngester\x12\x66\n\x0fProcessDocument\x12\'.nexus.document_service.DocumentRequest\x1a(.nexus.document_service.ProcessingStatus0\x01\x42p\n\x1a\x63om.nexus.document_serviceB\x14\x44ocumentServiceProtoP\x01Z:github.com/sambit-mondal/nexus-copilot/pb/document_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.nexus.document_serviceB\024DocumentServiceProtoP\001Z:github.com/sambit-mondal/nexus-copilot/pb/document_service'
  _globals['_DOCUMENTREQUEST']._serialized_start=50
  _globals['_DOCUMENTREQUEST']._serialized_end=126
  _globals['_PROCESSINGSTATUS']._serialized_start=128
  _globals['_PROCESSINGSTATUS']._serialized_end=248
  _globals['_DOCUMENTINGESTER']._serialized_start=250
  _globals['_DOCUMENTINGESTER']._serialized_end=372
# @@protoc_insertion_point(module_scope)
